// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zit.AgencyManager.Dados.Banco;

#nullable disable

namespace Zit.AgencyManager.Dados.Migrations
{
    [DbContext(typeof(AgencyManagerContext))]
    partial class AgencyManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zit.AgencyManager.Dominio.Modelos.Agencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(90)");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Agencias", (string)null);
                });

            modelBuilder.Entity("Zit.AgencyManager.Dominio.Modelos.Caixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aberto")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("TrocoFinal")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("TrocoInicial")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("varchar(90)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Caixa", (string)null);
                });

            modelBuilder.Entity("Zit.AgencyManager.Dominio.Modelos.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Atribuicoes")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(90)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Cargos", (string)null);
                });

            modelBuilder.Entity("Zit.AgencyManager.Dominio.Modelos.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgenciaId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<int>("CargoId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DataAdmissao")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataDemissao")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(90)");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasColumnType("varchar(90)");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("CargoId");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Colaboradores", (string)null);
                });

            modelBuilder.Entity("Zit.AgencyManager.Dominio.Modelos.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgenciaId")
                        .HasColumnType("int");

                    b.Property<int?>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("varchar(90)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(90)");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("TipoContato")
                        .IsRequired()
                        .HasColumnType("varchar(90)");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Contatos", (string)null);
                });

            modelBuilder.Entity("Zit.AgencyManager.Dominio.Modelos.ContratoAgenciaEmpresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgenciaId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<decimal>("Comissao")
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateOnly>("DataContrato")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataDistrato")
                        .HasColumnType("date");

                    b.Property<bool>("EmiteNota")
                        .HasColumnType("bit");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("FrequenciaAcerto")
                        .IsRequired()
                        .HasColumnType("varchar(90)");

                    b.Property<string>("ModalidadeAcerto")
                        .IsRequired()
                        .HasColumnType("varchar(90)");

                    b.Property<string>("ModalidadeComissao")
                        .IsRequired()
                        .HasColumnType("varchar(90)");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("ContratosAgenciaEmpresa", (string)null);
                });

            modelBuilder.Entity("Zit.AgencyManager.Dominio.Modelos.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("varchar(90)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("varchar(90)");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("Zit.AgencyManager.Dominio.Modelos.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(90)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("varchar(90)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(90)");

                    b.Property<string>("Complemento")
                        .HasColumnType("varchar(90)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(90)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(90)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("varchar(90)");

                    b.HasKey("Id");

                    b.ToTable("Enderecos", (string)null);
                });

            modelBuilder.Entity("Zit.AgencyManager.Dominio.Modelos.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(90)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("varchar(90)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(90)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("varchar(90)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("varchar(90)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("varchar(90)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(90)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("varchar(90)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(90)");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Zit.AgencyManager.Dominio.Modelos.Agencia", b =>
                {
                    b.HasOne("Zit.AgencyManager.Dominio.Modelos.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Zit.AgencyManager.Dominio.Modelos.Caixa", b =>
                {
                    b.HasOne("Zit.AgencyManager.Dominio.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Zit.AgencyManager.Dominio.Modelos.Colaborador", b =>
                {
                    b.HasOne("Zit.AgencyManager.Dominio.Modelos.Agencia", "Agencia")
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zit.AgencyManager.Dominio.Modelos.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zit.AgencyManager.Dominio.Modelos.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agencia");

                    b.Navigation("Cargo");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Zit.AgencyManager.Dominio.Modelos.Contato", b =>
                {
                    b.HasOne("Zit.AgencyManager.Dominio.Modelos.Agencia", null)
                        .WithMany("Contatos")
                        .HasForeignKey("AgenciaId");

                    b.HasOne("Zit.AgencyManager.Dominio.Modelos.Colaborador", null)
                        .WithMany("Contatos")
                        .HasForeignKey("ColaboradorId");

                    b.HasOne("Zit.AgencyManager.Dominio.Modelos.Empresa", null)
                        .WithMany("Contatos")
                        .HasForeignKey("EmpresaId");
                });

            modelBuilder.Entity("Zit.AgencyManager.Dominio.Modelos.ContratoAgenciaEmpresa", b =>
                {
                    b.HasOne("Zit.AgencyManager.Dominio.Modelos.Agencia", "Agencia")
                        .WithMany("Empresas")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zit.AgencyManager.Dominio.Modelos.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agencia");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Zit.AgencyManager.Dominio.Modelos.Empresa", b =>
                {
                    b.HasOne("Zit.AgencyManager.Dominio.Modelos.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Zit.AgencyManager.Dominio.Modelos.Usuario", b =>
                {
                    b.HasOne("Zit.AgencyManager.Dominio.Modelos.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("Zit.AgencyManager.Dominio.Modelos.Agencia", b =>
                {
                    b.Navigation("Contatos");

                    b.Navigation("Empresas");
                });

            modelBuilder.Entity("Zit.AgencyManager.Dominio.Modelos.Colaborador", b =>
                {
                    b.Navigation("Contatos");
                });

            modelBuilder.Entity("Zit.AgencyManager.Dominio.Modelos.Empresa", b =>
                {
                    b.Navigation("Contatos");
                });
#pragma warning restore 612, 618
        }
    }
}
